---
version: "2"
services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80

  jspring:
    container_name: jspring
    build: ./jspring
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=jspring
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jspring
      - SPRING_DATASOURCE_USERNAME=jspring
      - SPRING_DATASOURCE_PASSWORD=am5ureevaoThu9egahNg
    ports:
      - 8081:8080
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=jspring
      - POSTGRES_USER=jspring
      - POSTGRES_PASSWORD=am5ureevaoThu9egahNg

  otel-collector:
    container_name: otel
    image: otel/opentelemetry-collector:0.66.0
    command: [ "--config=/etc/otel-collector.yml" ]
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml:ro

  tempo:
    container_name: tempo
    image: grafana/tempo:1.5.0
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.40.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.6
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
